# Generated by Django 6.0.6 on 2026-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('quiz_result', 'Quiz result'), ('proctoring', 'Proctoring alert'), ('risk', 'Dropout risk'), ('system', 'System')], default='system', max_length=40),
        ),
    ]
