# Generated by Django 6.0.6 on 2026-06-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('mark_scheme', models.TextField(help_text='Official rubric the grader scores against. One criterion per line. Never exposed to students through the API.')),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_questions', to='core.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_answer_questions', to='core.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faces', models.PositiveIntegerField()),
                ('verdict', models.CharField(choices=[('ok', 'OK'), ('no_face', 'No face'), ('multiple_faces', 'Multiple faces')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='core.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='core.quiz')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['quiz', 'enrollment', 'created_at'], name='core_procto_quiz_id_598327_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('criteria_met', models.JSONField(blank=True, default=list)),
                ('criteria_missing', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('engine', models.CharField(choices=[('llm', 'Fine-tuned LLM'), ('heuristic', 'Criterion overlap')], default='heuristic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_submissions', to='core.enrollment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.shortanswerquestion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'enrollment'], name='core_shorta_questio_3e358a_idx')],
            },
        ),
    ]
