# Generated by Django 6.0.6 on 2026-06-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shortanswerquestion_proctoringlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Per-question detail: {question_id: {selected, correct, topic}} — the raw material for weak-topic analytics.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.CharField(blank=True, help_text="Syllabus topic, e.g. 'Kinematics' — powers weak-topic practice.", max_length=100),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='topic',
            field=models.CharField(blank=True, help_text="Syllabus topic, e.g. 'Kinematics' — powers weak-topic practice.", max_length=100),
        ),
    ]
