# Generated by Django 6.0.6 on 2026-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quizattempt_answers_quizquestion_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Exam mode: countdown with auto-submit. Blank = untimed.', null=True),
        ),
    ]
