# Generated by Django 6.0.6 on 2026-06-11 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_seed_badges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('probability', models.FloatField(help_text='Model dropout probability (0-1).')),
                ('features', models.JSONField(default=dict, help_text='Engagement features the prediction was made from.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Outreach notes from the instructor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='engagement__status_92a5d8_idx')],
            },
        ),
    ]
