# Generated by Django 6.0.6 on 2026-06-11 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_remediationticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remediationticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'contacted'))), fields=('student',), name='one_unresolved_ticket_per_student'),
        ),
    ]
