# Generated by Django 6.0.6 on 2026-06-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutormessage',
            name='feedback_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['feedback', 'created_at'], name='tutor_tutor_feedbac_beabea_idx'),
        ),
    ]
