# Generated by Django 6.0.6 on 2026-06-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_quizattempt_answers_quizquestion_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('front', models.TextField(help_text='The prompt side — a question or cue.')),
                ('back', models.TextField(help_text='The answer side.')),
                ('source', models.CharField(choices=[('llm', 'AI-generated'), ('heuristic', 'Auto-extracted'), ('instructor', 'Instructor-written')], default='instructor', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='core.lesson')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.FloatField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField()),
                ('last_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='revision.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['course', 'is_published'], name='revision_fl_course__42fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcard',
            index=models.Index(fields=['user', 'due_at'], name='revision_re_user_id_3cf6d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcard',
            unique_together={('user', 'flashcard')},
        ),
    ]
